### ISSUE TITLE
Can't attache file to a message

### ISSUE THREAD

**Issue by frediz** [paullouisageneau/Teapotnet#6]
Hi,
I recompiled a package for debian based on the latest git tree.
Once teapotnet installed and started, I can create a user, but when I try attach a file, there's
nothing appearing in the little box supposed to mention it except a "/" that also appears in the message text box.
If I send that, the message is posted but instead of the picture I see "Loading attachment.../"
On the server, the file seems to be in the _upload directory.

F.

**Comment by paullouisageneau** [comment]
Hi,
Thank you for your feedback ! The issue is now fixed in master, so uploaded files should be properly attached to messages.
